name: 'Setup Playwright for Wallet Tests'
description: 'Robust Playwright setup for wallet/MetaMask testing'
runs:
  using: 'composite'
  steps:
    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'] || require('./package.json').dependencies['@playwright/test'] || '1.48.0')")
        echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
        echo "Playwright version: $PLAYWRIGHT_VERSION"

    - name: Clean and Install Playwright browsers
      shell: bash
      run: |
        echo "Cleaning Playwright cache..."
        rm -rf ~/.cache/ms-playwright || true
        
        echo "Installing Playwright browsers and dependencies..."
        # Install system dependencies first
        pnpm exec playwright install-deps chromium
        
        # Then install the browser
        pnpm exec playwright install chromium
        
        echo "Verifying installation..."
        pnpm exec playwright --version
        
        # List installed browsers
        echo "Installed browsers:"
        ls -la ~/.cache/ms-playwright/ 2>/dev/null || true
        
        # Double-check the chromium executable exists
        CHROMIUM_PATH=$(find ~/.cache/ms-playwright -name "chrome" -type f 2>/dev/null | head -1)
        if [ -z "$CHROMIUM_PATH" ]; then
          echo "ERROR: Chromium executable not found after installation!"
          echo "Attempting force reinstall..."
          pnpm exec playwright install --force chromium
        else
          echo "Chromium found at: $CHROMIUM_PATH"
          ls -la "$CHROMIUM_PATH"
        fi

    - name: Install additional dependencies for MetaMask
      shell: bash
      run: |
        echo "Installing additional dependencies for MetaMask..."
        # These are often needed for MetaMask extension (Ubuntu 24.04 compatible)
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libasound2t64 \
          fonts-liberation \
          libappindicator3-1 \
          xdg-utils \
          ca-certificates \
          libdrm2 \
          libxss1 \
          lsb-release
