name: Wallet Tests (Playwright Action)

on:
  workflow_dispatch:
  push:
    paths:
      - 'e2e/specs/wallets/**'
      - '.github/workflows/test-wallet-playwright.yaml'

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  wallets-playwright-action:
    name: wallets (Using Playwright Action)
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Playwright using official action
        uses: microsoft/playwright-github-action@v1
        with:
          browsers: chromium

      - name: Setup virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Verify Playwright installation
        run: |
          echo "Checking Playwright installation..."
          pnpm exec playwright --version
          
          echo "Checking browser installations..."
          pnpm exec playwright show-report || true
          
          echo "Cache contents:"
          ls -la ~/.cache/ms-playwright/ || echo "No cache found"
          
          # Test that we can actually launch chromium
          echo "Testing chromium launch..."
          cat > test-launch.js << 'EOF'
          const { chromium } = require('@playwright/test');
          (async () => {
            console.log('Attempting to launch chromium...');
            const browser = await chromium.launch({ headless: true });
            console.log('✅ Chromium launched successfully!');
            await browser.close();
            process.exit(0);
          })().catch(err => {
            console.error('❌ Failed to launch chromium:', err);
            process.exit(1);
          });
          EOF
          node test-launch.js

      - name: Run wallet tests
        run: |
          parallel --lb --halt now,success=1,fail=1 ::: \
          "pnpm dev" \
          "pnpm wait-on http://localhost:3000 && pnpm e2e:wallet --headed"
        env:
          SECRET_WORDS: ${{ secrets.SECRET_WORDS }}
          DISPLAY: :99

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wallets-report-playwright-action
          path: |
            playwright-report/
            test-results/
            *.png
          retention-days: 30